SYSprint("WAR_CATS","WELCOME TO WAR_CATS")
SYSwrite("CHOSE YOUR CLAN: RIVER CLAN: A CLAN OF EXCELLENT SWIMMERS WHO MAKE THEIR HOME ON THE BANKS OF THE FOREST TERRITORY'S RIVER. TYPE R TO BE A PART OF THIS CLAN!")
SYSprint("SYSTEM","PROGRAM EXITED")