--DO NOT RENAME THIS FILE OR THE PROGRAM WILL ERROR
--os.execute("clear")
print("BOOTING UP")
require("CORE/DEF")
wait(1)
SYSprint("BOOT SYSTEM","RUNNING ".. _VERSION)
require("CORE/SECURE_BOOT_CORE")