SYSprint("SECURE BOOT SYSTEM","STARTING SECURE BOOT")
if os.getenv("OS_SECURE_BOOT_KEY") == os.getenv("BIOS_MAIN_OS_SECURE_BOOT_KEY") then
	SYSprint("SECURE BOOT SYSTEM","KEY VALIDADATED")
	SYSprint("SECURE BOOT SYSTEM","WAITING FOR CORE_CONFIG_FILES")
	require("CORE/CORE_CONFIG_FILES/BOOT_CONFIG")
	SYSprint("SECURE BOOT SYSTEM","SECURE BOOT DONE")
	if os.getenv("DEBUGER_ACCESSABLE") == "true" then
		SYSprint("BOOT SYSTEM","LOADING DEBUGER. TYPE debug = nil (FOR SECURITY TO PREVENT PPL FROM MESSING WITH THE OS ONCE BOOTED UP) THEN cont TO CONTINUE TO OS NOTE: IF YOU SEE A MESSAGE ON YOUR SCREEN SAYING TO ENTER SOMETHING ON THE PROMPT AND THE PROMPT SAYS LUA_DEBUG AND SAYS SOMTHING OTHER THAIN BOOT SYSTEM DONT DO IT! IT CULD LOAD A VIRUS OR CRASH YOUR SYSTEM!!")

		debug.debug()
		if debug == nil then
		else
			C_ERROR("44454255475f4e4f545f53454355524544")
		end
		else
		debug = nil
	end

	SYSprint("SECURE BOOT SYSTEM","CLEARING CONSOLE IF CLR_ON_BOOT_DONE TRUE")
	if CLR_ON_BOOT_DONE then
		os.execute("clear")
	end
	require("CORE/CORE_OS/MAIN_OS")
else
	SYSprint("SECURE BOOT SYSTEM","ERROR: SBK IS NOT APPROVED")
	SYSprint("SECURE BOOT SYSTEM","SECURE BOOT FAILED")
	C_ERROR("53424b5f49535f4e4f545f415050524f564544")
	end
